First commit.

diff --git a/locale/Makefile b/locale/Makefile
--- a/locale/Makefile
+++ b/locale/Makefile
@@ -8,6 +8,7 @@ include PACKAGE
 CATALOGS  = $(LINGUAS)
 MO_FILES = $(addsuffix .gmo, $(LINGUAS))
 
+MSGINIT = msginit
 MSGMERGE = msgmerge
 MSGFMT   = msgfmt
 XGETTEXT = xgettext
@@ -38,7 +39,7 @@ clean:
 
 $(TD).pot: $(POTFILES)
 	$(XGETTEXT) --output=$(srcdir)/$(TD).pox --from-code=utf-8 \
-		--language=Perl --indent --force-po \
+		--language=Perl \
 		--add-comments=TRANSLATORS: --files-from=$(srcdir)/POTFILES \
 		--copyright-holder="$(COPYRIGHT_HOLDER)" \
 		--msgid-bugs-address="$(MSGID_BUGS_ADDRESS)" \
@@ -49,15 +50,22 @@ $(TD).pot: $(POTFILES)
 		--keyword=N__p:1c,2 --keyword=N__np:1c,2,3 --keyword=%__ && \
 	rm -f $@ && mv $(TD).pox $@
 
+init:
+	languages='$(LINGUAS)'; \
+	for lang in $$languages; do \
+		$(MSGINIT) --locale $$lang --no-translator -o $$lang.po; \
+		cp -a $$lang.po $$lang.old.po; \
+	done
+
 install: $(MO_FILES)
 	cd $(srcdir); \
 	languages='$(LINGUAS)'; \
 	for lang in $$languages; do \
-		mkdir "LC_MESSAGES/$$lang" \
-		dest="LC_MESSAGES/$$lang/$(TD).mo"; \
-		cat="$$lang.gmo"; \
-		echo "installing $$cat as $$dest"; \
-		cp -f $$cat $$dest && chmod 644 $$dest || exit 1; \
+			mkdir -p "$$lang/LC_MESSAGES" || exit 1; \
+			dest="$$lang/LC_MESSAGES/$(TD).mo"; \
+			cat="$$lang.gmo"; \
+			echo "installing $$cat as $$dest"; \
+			cp -f $$cat $$dest && chmod 644 $$dest || exit 1; \
 	done
 
 update-mo: $(MO_FILES)
@@ -65,17 +73,23 @@ update-mo: $(MO_FILES)
 update-po:
 	$(MAKE) $(TD).pot
 	cd $(srcdir); \
-	for lang in $$languages; do \
-	  mv $$lang.po $$lang.old.po; \
-	  echo "$$lang:"; \
-	  if $(MSGMERGE) --no-wrap $$lang.old.po $(TD).pot -o $$lang.po; then \
-		rm -f $$lang.old.po; \
-	  else \
-		echo "msgmerge for $$lang failed!"; \
-		rm -f $$lang.po; \
-		mv $$lang.old.po $$lang.po; \
-	  fi; \
+	catalogs='$(CATALOGS)'; \
+	for cat in $$catalogs; do \
+		cat=`basename $$cat`; \
+		lang=`echo $$cat | sed 's/\$(CATOBJEXT)$$//'`; \
+		mv $$lang.po $$lang.old.po; \
+		echo "$$lang:"; \
+		if $(MSGMERGE) --no-wrap $$lang.old.po $(TD).pot -o $$lang.po; then \
+			rm -f $$lang.old.po; \
+		else \
+			echo "msgmerge for $$cat failed!"; \
+			rm -f $$lang.po; \
+			mv $$lang.old.po $$lang.po; \
+		fi; \
 	done
+
+
+
 
 .SUFFIXES:
 .SUFFIXES: .po .gmo
